delimiter $$

CREATE TABLE `AUTH_USERS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(255) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_NAME` (`USER_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$

delimiter $$

CREATE TABLE `AUTH_GROUPS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `GRP_NAME` varchar(255) DEFAULT NULL,
  `GRP_DESC` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `GRP_NAME` (`GRP_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$

delimiter $$

CREATE TABLE `AUTH_USER_GROUPS` (
  `AUTH_USER_ID` bigint(20) NOT NULL,
  `AUTH_GROUP_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`AUTH_USER_ID`,`AUTH_GROUP_ID`),
  KEY `FK_AUTH_GROUP` (`AUTH_GROUP_ID`),
  KEY `FK_AUTH_USER` (`AUTH_USER_ID`),
  CONSTRAINT `CONST_FK_AUTH_GROUP` FOREIGN KEY (`AUTH_GROUP_ID`) REFERENCES `AUTH_GROUPS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `CONST_FK_AUTH_USER` FOREIGN KEY (`AUTH_USER_ID`) REFERENCES `AUTH_USERS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE=InnoDB DEFAULT CHARSET=utf8$$

delimiter $$

CREATE VIEW `VIEW_USER_ROLE` AS
SELECT  U.USER_NAME, U.PASSWORD, G.GRP_NAME
 FROM `AUTH_USER_GROUPS` UG 
 INNER JOIN `AUTH_USERS` U ON U.ID = UG.AUTH_USER_ID
 INNER JOIN `AUTH_GROUPS` G ON G.ID =  UG.AUTH_GROUP_ID$$